os: 'Windows'
tts_package: 'pyttsx3'
stimuli_dir: 'data/lang_sound/'

right_keep_path: 'data/static/right_keep.mp3'
right_stop_path: 'data/static/right_stop.mp3'
left_keep_path: 'data/static/left_keep.mp3'
left_stop_path: 'data/static/left_stop.mp3'
beep_path: 'data/static/sample_beep.mp3'

patient_note_path: 'data/patient_df.csv'
