# INPUT CHANGES HERE

os: 'os' # 'windows' or 'linux' or 'os'
# Define your output path:
patient_df_path: 'data/patient_df.csv'  # Adjust the path if your file is in a different location
patient_note_path: 'data/patient_notes.csv' # Adjust the path if your file is in a different location

#------------------------------

# (Do not change)
tts_package: 'pyttsx3'
stimuli_dir: 'data/lang_trials/'

sentences_path: 'data/sentences'
right_keep_path: 'data/static/right_keep.mp3'
right_stop_path: 'data/static/right_stop.mp3'
left_keep_path: 'data/static/left_keep.mp3'
left_stop_path: 'data/static/left_stop.mp3'
beep_path: 'data/static/sample_beep.mp3'

